### ISSUE TITLE
AWS部署 global.js

### ISSUE THREAD

**Issue by lizhaoguo6** [efwGrp/efw4.X#43]
AWS 部署 Elastic Beanstalk环境时 报错 
23-Mar-2021 02:43:17.027 SEVERE [localhost-startStop-1] efw.framework.init ScriptManager failed. jar:file:/var/lib/tomcat8/webapps/ROOT/WEB-INF/lib/efw-4.03.001.jar!/efw/resources/server/efw.server.event.js:117 TypeError: e.getClass is not a function

**Comment by changkejun** [comment]
4.04.003 で対応
