### ISSUE TITLE
rest client　リクエストボディに日本語があると例外が発生する

### ISSUE THREAD

**Issue by kn0412** [efwGrp/efw4.X#46]

**Comment by kn0412** [comment]
ここで発生していると思います
RestManager.java : line 57
`outputStream.write(param.getBytes());`

文字コードを指定すれば直ると思います
`outputStream.write(param.getBytes(java.nio.charset.StandardCharsets.UTF_8));`

**Comment by changkejun** [comment]
4.04.005をアップロードします。解凍して使ってみてください。OKなら、正式にmasterにアップします。

[efw-4.04.005.zip](https://github.com/efwGrp/efw4.X/files/6219666/efw-4.04.005.zip)

**Comment by kn0412** [comment]
ありがとうございます。
直りました。
