### ISSUE TITLE
DB検索時、パラメーターなしで省略するか

### ISSUE THREAD

**Issue by sogainjapan** [efwGrp/efw4.X#52]
タイトル通りに、DBを検索する時、パラメーターがなし場合、②ようにできますか

①db . select ( groupId , sqlId , params )  ⇒　パラメーターあり

②db . select ( groupId , sqlId )  ⇒　パラメーターなし

よろしくお願いいたします。

**Comment by changkejun** [comment]
できないとわかりました。
db . select ( sql , jdbcResourceName )があるから。２つパラメータなら一種類しかできません。
