### ISSUE TITLE
ヘルプの修正依頼（Result.attach）

### ISSUE THREAD

**Issue by spinpreach** [efwGrp/efw4.X#97]
https://github.com/efwGrp/efw4.X/blob/master/help/result.attach.md

「isAbs」の説明が不十分です。
型がbooleanで、どちらかが「相対パス or 絶対パス」であるなら、
初期値が「true or false」どちらなのか？ そして「相対パス or 絶対パス」なのか？
記載すべきです。

**Comment by changkejun** [comment]
absは、absoluteの略です。そして、isabsは、is絶対パスの意味です。つまり、trueは絶対パスです。
